@startuml

Menü -> Person :login()
Person --> Menü : boolean false
Menü -> Person : registrieren()
Person --> Menü : boolean
Person -> Konto : ausZahlen(int betrag)  
Konto --> Person : boolean
Person -> Konto : einZahlen(int betrag)
Konto --> Person : boolean
Person -> Konto : abheben
Konto -> Portfolio : ausZahlen()
Portfolio --> Konto : booean
Konto -> Portfolio : einZahlen()
Portfolio --> Konto : boolean
Portfolio -> Menü
Menü -> Person : abmelden()
Person --> Menü : boolean
Menü -> Gson:

@enduml

@startuml

Menü -> Person : login()
Person --> Menü : boolean
Menü -> Person : registrieren()
Person --> Menü : boolean
Anmelden -> Menü 
Menü -> MenüFinanzen : input() 
MenüFinazen -> KaufuVerkaufen :input()
KaufuVerkaufen -> AktienMarkt 
AktienMarkt -> Person : string (Welche Aktie Willst du Kaufen.Verkaufen ?)
Person -> AktienMarkt : input() 
AktienMarkt -> Person : string (Wie Viele Aktien willst du Kaufen.Verkaufen)  
AktienMarkt-> Lequide.Mittel: scan()
Lequide.Mittel --> AktienMarkt: boolean Fals
Lequide.Mittel -> Person : string (Das Aufgeladene Geld reicht nicht aus)
Lequide.Mittel --> AktienMarkt: boolean true
Lequide.Mittel -> AktienMarkt: kauf()
AktienMarkt -> Lequide.Mittel: Value (Lequide.Miitel - value stock * Anzahl stock)
AktienMarkt -> Portfolio : transfer()
Lequide.Mittel -> Person : string (Value)
Portfolio -> Person : string (Anzahl Stock, Value Stock) 
AktienMarkt -> Zurück: input()
Zurück -> MenüFinanzen
MenüFinanzen -> Zurück : input()
Zurück -> Menü 
Menü -> Abmelden : input()
Abmelden -> Person

@enduml

@startuml

Person -> Anmelden :login()
Anmelden --> Person : boolean true
Person -> registrieren :registrieren()
registrieren -> Person :string() 
Person -> Anmelden  :login()
Anmelden -> Menü 
Menü -> MenüAktien: input()
MenüAktien -> Kurse: input()
Kurse -> AktienMarket : show()
AktienMarket -> Zurück: input()
Zurück -> MenüAktien:
MenüAktien -> Zurück: input()
Zurück -> Menü
Menü -> Abmelden: input()
Abmelden -> Person  

@enduml

@startuml

Person -> Anmelden :login()
Anmelden --> Person : boolean true
Person -> registrieren :registrieren()
registrieren -> Person :string() 
Person -> Anmelden  :login()
Anmelden -> Menü 
Menü -> MenüAktien: input()
MenüAktien -> Portfolio: input()
Portfolio -> Aktien : show()
Aktien -> Zurück: input()
Zurück -> MenüAktien: 
MenüAktien -> Zurück: input()
Zurück -> Menü: 
Menü -> Abmelden : input()
Abmelden -> Person 

@enduml